export const ADD_LOAN_SUB_CATEGORY_REQUEST = "ADD_LOAN_SUB_CATEGORY_REQUEST";
export const ADD_LOAN_SUB_CATEGORY_SUCCESS = "ADD_LOAN_SUB_CATEGORY_SUCCESS";
export const ADD_LOAN_SUB_CATEGORY_FAIL = "ADD_LOAN_SUB_CATEGORY_FAIL";

export const DELETE_LOAN_SUB_CATEGORY_REQUEST =
  "DELETE_LOAN_SUB_CATEGORY_REQUEST";
export const DELETE_LOAN_SUB_CATEGORY_SUCCESS =
  "DELETE_LOAN_SUB_CATEGORY_SUCCESS";
export const DELETE_LOAN_SUB_CATEGORY_FAIL = "DELETE_LOAN_SUB_CATEGORY_FAIL";

export const CHANGE_STATUS_LOAN_SUB_CATEGORY_REQUEST =
  "CHANGE_STATUS_LOAN_SUB_CATEGORY_REQUEST";
export const CHANGE_STATUS_LOAN_SUB_CATEGORY_SUCCESS =
  "CHANGE_STATUS_LOAN_SUB_CATEGORY_SUCCESS";
export const CHANGE_STATUS_LOAN_SUB_CATEGORY_FAIL =
  "CHANGE_STATUS_LOAN_SUB_CATEGORY_FAIL";

export const FIND_ALL_LOAN_SUB_CATEGORY_REQUEST =
  "FIND_ALL_LOAN_SUB_CATEGORY_REQUEST";
export const FIND_ALL_LOAN_SUB_CATEGORY_SUCCESS =
  "FIND_ALL_LOAN_SUB_CATEGORY_SUCCESS";
export const FIND_ALL_LOAN_SUB_CATEGORY_FAIL =
  "FIND_ALL_LOAN_SUB_CATEGORY_FAIL";

export const FIND_ONE_LOAN_SUB_CATEGORY_REQUEST =
  "FIND_ONE_LOAN_SUB_CATEGORY_REQUEST";
export const FIND_ONE_LOAN_SUB_CATEGORY_SUCCESS =
  "FIND_ONE_LOAN_SUB_CATEGORY_SUCCESS";
export const FIND_ONE_LOAN_SUB_CATEGORY_FAIL =
  "FIND_ONE_LOAN_SUB_CATEGORY_FAIL";

export const UPDATE_LOAN_SUB_CATEGORY_REQUEST =
  "UPDATE_LOAN_SUB_CATEGORY_REQUEST";
export const UPDATE_LOAN_SUB_CATEGORY_SUCCESS =
  "UPDATE_LOAN_SUB_CATEGORY_SUCCESS";
export const UPDATE_LOAN_SUB_CATEGORY_FAIL = "UPDATE_LOAN_SUB_CATEGORY_FAIL";
